github.com:
    users:
        itsvrushabh:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: itsvrushabh
