github.com:
    users:
        itsvrushabh:
            oauth_token: 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
    git_protocol: ssh
    user: itsvrushabh
    oauth_token: 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
