github.com:
    users:
        itsvrushabh:
            oauth_token: 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
    git_protocol: ssh
    user: itsvrushabh
    oauth_token: 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
