wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wall/fighter-jet-pilot-5120x2880-24341.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wall/iron-man-red-glow-5120x2880-24338.png
    fit_mode = cover
}
