general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# 1. Dim brightness (3 minutes)
listener {
    timeout = 180                                
    on-timeout = brightnessctl set 10%          # set monitor to 10%
    on-resume = brightnessctl set 100%          # restore brightness
}

# 2. Lock Screen (5 minutes)
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session          # lock screen with hyprlock
}

# 3. Turn off monitors (10 minutes)
listener {
    timeout = 600                                
    on-timeout = hyprctl dispatch dpms off       # displays to sleep
    on-resume = hyprctl dispatch dpms on         # wake displays
}
