# Normal colors during the day
profile {
    time = 07:00
    identity = true
}

# Evening warm-up
profile {
    time = 19:00
    temperature = 5000
}

# Night mode (Deep orange)
profile {
    time = 22:30
    temperature = 3500
}
